uwsgi:
    image: madron/django-example
    volumes:
        - /media
        - /run/uwsgi
    environment:
        - DEBUG=True
    command: >
        uwsgi
        --plugins /usr/lib/uwsgi/python_plugin.so
        --master
        --processes 1
        --threads 1
        --listen 128
        --chdir /src
        --wsgi settings.wsgi
        --http-socket :8000
        --uwsgi-socket :3031
        --uwsgi-socket /run/uwsgi/uwsgi.sock
        --chmod-socket
        --stats :9191

nginx:
    image: madron/django-example
    volumes_from:
        - uwsgi
    links:
        - uwsgi
    ports:
        - '8000:80'  # http protocol
        - '8001:81'  # uwsgi protocol over tcp
        - '8002:82'  # uwsgi protocol over unix socket
    command: nginx
